site_name: Databook
site_url: https://databook.kavakci.dev
docs_dir: src
repo_url: https://github.com/dybdeskarphet/databook
repo_name: dybdeskarphet/databook
edit_uri: edit/main/src/
use_directory_urls: false
plugins: 
  - social:
      cards_layout_options:
        logo: assets/logo.png
  - search
  - mkdocs-jupyter:
          execute: true
          include_requirejs: true
          custom_mathjax_url: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-AMS_CHTML-full,Safe" 
  - offline
markdown_extensions: 
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - footnotes
theme:
  name: material
  icon:
    logo: material/google-analytics
    annotation: material/circle-medium
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.prune 
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
  language: tr
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
nav:
  - Introduction: index.md
  - Practices:
    - 00_movie_analysis.ipynb
    - Exploratory Data Analysis: 
      - 01_location_estimates.ipynb
      - 02_variability_estimates.ipynb
      - 03_exploring_data_distribution.ipynb
      - Handwritten Notes: notes/01_exploratory_data_analysis.pdf

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js