"""
This type stub file was generated by pyright.
"""

from ._pls import CCA, PLSCanonical, PLSRegression, PLSSVD

"""Algorithms for cross decomposition."""
__all__ = ["CCA", "PLSSVD", "PLSCanonical", "PLSRegression"]
